<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

/**
 * @property-read int $id
 * @property Parser $parser
 * @property string $table_name
 * @property int $parser_id
 * @property int $rows_count
 * @property string $output_path
 */
class ParserTask extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public function parser() {
        return $this->belongsTo(Parser::class);
    }

    public function __get($key)
    {
        if($key == 'count_before') {
            return Cache::get("task-count-$this->id", 0);
        } elseif ($key == 'speed') {
            return Cache::get("speed-$this->id", 0);
        }
        return parent::__get($key); // TODO: Change the autogenerated stub
    }
}
